name: Build AVF Guest Kernel

on: workflow_dispatch

env:
  KERNEL_DIR_NAME: android16-guest-kernel

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo '::notice::Removing unnecessary packages and files to free disk space…'

          echo '::group::Cleanup'

          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /opt/hostedtoolcache /usr/local/share/boost /usr/local/graalvm \
            /usr/local/share/chromium /usr/local/.ghcup /usr/share/swift \
            /usr/local/julia* /usr/lib/jvm /opt/microsoft /opt/az

          sudo apt-get autoremove -y '^dotnet-.*' '^llvm-.*' 'php.*' azure-cli google-chrome-stable \
            firefox powershell mono-devel || :

          echo '::endgroup::'

          echo '::notice::Disk space after cleanup'
          df -h /

      - name: Install dependencies
        run: |
          sudo apt-get install -U -y bc bison build-essential cpio flex \
            libelf-dev libssl-dev lz4 python3 python3-pip wget git repo

      - name: Clone kernel source with repo
        run: |
          mkdir -p "$KERNEL_DIR_NAME"
          cd "$KERNEL_DIR_NAME"
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android16-6.12
          repo sync -c -j$(nproc)

      - name: Build kernel
        working-directory: ${{ env.KERNEL_DIR_NAME }}
        run: |
          cp -v ../build-kernel.sh ./
          cp -v ../kernel-config.txt ./original-config-from-phone.txt
          bash build-kernel.sh

      - name: Upload vmlinuz artifact
        uses: actions/upload-artifact@v4
        with:
          name: vmlinuz-docker
          path: ${{ env.KERNEL_DIR_NAME }}/vmlinuz
          if-no-files-found: error
